#!/bin/sh
#Исправляем проблему запоминания яркости Ubuntu
echo "#ИСПРАВЛЯЕМ ПРОБЛЕМУ ЗАПОМИНАНИЯ ЯРКОСТИ UBUNTU..."
sudo cp ../config/brightness/brightness.service /etc/systemd/system/
sudo systemctl enable brightness.service 
sudo systemctl start brightness.service